config/routes.rb
Rails.application.routes.draw do
  resources :movieus, only: [:index, :show]
  resources :sames, only: [:index, :show]
  resources :tonans, only: [:index, :show]
  resources :melodies, only: [:index, :show]
  resources :awsubs, only: [:index, :show]
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'

  root 'pages#home'

  resources :oploverzs, only: [:index, :show]
  end

app/models/aimage.rb
class Aimage < ApplicationRecord
  validates :url, :awsub_id, uniqueness: true
  belongs_to :awsub
end

app/models/awsub.rb
class Awsub < ApplicationRecord

  extend FriendlyId

  friendly_id :title, use: [:slugged, :history, :finders]

  def should_generate_new_friendly_id?
    title_changed?
  end

  validates :title, :asmall, :amedium, uniqueness: true
  validates :title,  presence: true
  has_many :aimages, dependent: :destroy

  # searchable do
  #   text :title
  # end
end

app/models/limage.rb
class Limage < ApplicationRecord
  belongs_to :same
  validates :url, :same_id, uniqueness: true
end

app/models/melody.rb
class Melody < ApplicationRecord

  extend FriendlyId

  friendly_id :mtitle, use: [:slugged, :history, :finders]

  def should_generate_new_friendly_id?
    mtitle_changed?
  end


  validates :mtitle, uniqueness: true
  validates :mtitle, presence: true

  has_many :mimages, dependent: :destroy

  # searchable do
  #   text :mtitle
  # end
end

app/models/mimage.rb
class Mimage < ApplicationRecord
  validates :url, :melody_id, uniqueness: true
  
  belongs_to :melody

end

app/models/movieu.rb
class Movieu < ApplicationRecord

  extend FriendlyId

  friendly_id :title, use: [:slugged, :history, :finders]

  def should_generate_new_friendly_id?
    title_changed?
  end

  validates :title, uniqueness: true
  validates :title, presence: true
  has_many :vimages, dependent: :destroy
  
end

app/models/oimage.rb
class Oimage < ApplicationRecord
  validates :url, :oploverz_id, uniqueness: true
  belongs_to :oploverz
end

app/models/oploverz.rb
class Oploverz < ApplicationRecord

  extend FriendlyId

  friendly_id :title, use: [:slugged, :history, :finders]

  def should_generate_new_friendly_id?
    title_changed?
  end

  validates :title, uniqueness: true
  validates :title, presence: true
  has_many :oimages, dependent: :destroy
  has_many :ostreams, dependent: :destroy

  # searchable do
  #   text :title
  # end
end

app/models/ostream.rb
class Ostream < ApplicationRecord
  belongs_to :oploverz

  validates :link, :oploverz_id, uniqueness: true
end

app/models/same.rb
class Same < ApplicationRecord

  extend FriendlyId

  friendly_id :title, use: [:slugged, :history, :finders]

  def should_generate_new_friendly_id?
    title_changed?
  end

  validates :title, uniqueness: true
  validates :title, presence: true
  has_many :limages, dependent: :destroy

  # searchable do
  #   text :title
  # end
end

app/models/timage.rb
class Timage < ApplicationRecord
  validates :url, :tonan_id, uniqueness: true
  belongs_to :tonan
end

app/models/tonan.rb
class Tonan < ApplicationRecord

  extend FriendlyId

  friendly_id :title, use: [:slugged, :history, :finders]

  def should_generate_new_friendly_id?
    title_changed?
  end

  validates :title, :small, uniqueness: true
  validates :title, presence: true
  has_many :timages, dependent: :destroy

  # searchable do
  #   text :title
  # end
end

app/models/vimage.rb
class Vimage < ApplicationRecord
  belongs_to :movieu
  validates :url, :movieu_id, uniqueness: true
  validates :url, presence: true
end

app/controllers/aw_searcher.rb
# class AwSearcher
#   attr_reader :params, :awsubs
#   def call params
#     @params = params
#     @awsubs = simple_search
#     self
#   end
#
#   def simple_search
#     Awsub.search do
#     fulltext params[:q]
#     paginate(:page => params[:page], :per_page => 7)
#     end.results
#   end
#
# end

app/controllers/op_searcher.rb
# class OpSearcher
#   attr_reader :params, :oploverzs
#   def call params
#     @params = params
#     @oploverzs = simple_search
#     self
#   end
#
#   def simple_search
#     Oploverz.search do
#       fulltext params[:q]
#       paginate(:page => params[:page], :per_page => 7)
#   end.results
# end
#
# end

app/controllers/oploverzs_controller.rb
class OploverzsController < ApplicationController
  before_action :set_oploverz, only: [:show, :edit, :update, :destroy]

  # GET /oploverzs
  # GET /oploverzs.json
  def index
    # if params[:q].present?
    #   @oploverzs = OpSearcher.new.call(params).oploverzs
    # else
      @oploverzs = Oploverz.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 7)
    # end
  end

  # GET /oploverzs/1
  # GET /oploverzs/1.json
  def show
    @ostreams = @oploverz.ostreams
  end

  # GET /oploverzs/new
  def new
    @oploverz = Oploverz.new
  end

  # GET /oploverzs/1/edit
  def edit
  end

  # POST /oploverzs
  # POST /oploverzs.json
  def create
    @oploverz = Oploverz.new(oploverz_params)

    respond_to do |format|
      if @oploverz.save
        format.html { redirect_to @oploverz, notice: 'Oploverz was successfully created.' }
        format.json { render :show, status: :created, location: @oploverz }
      else
        format.html { render :new }
        format.json { render json: @oploverz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /oploverzs/1
  # PATCH/PUT /oploverzs/1.json
  def update
    respond_to do |format|
      if @oploverz.update(oploverz_params)
        format.html { redirect_to @oploverz, notice: 'Oploverz was successfully updated.' }
        format.json { render :show, status: :ok, location: @oploverz }
      else
        format.html { render :edit }
        format.json { render json: @oploverz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /oploverzs/1
  # DELETE /oploverzs/1.json
  def destroy
    @oploverz.destroy
    respond_to do |format|
      format.html { redirect_to oploverzs_url, notice: 'Oploverz was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_oploverz
      @oploverz = Oploverz.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def oploverz_params
      params.require(:oploverz).permit(:title, :sinops, :small, :medium)
    end
end

app/helpers/awsubs_helper.rb
module AwsubsHelper
end

app/helpers/melodies_helper.rb
module MelodiesHelper
end

app/helpers/movieus_helper.rb
module MovieusHelper
end

app/helpers/oploverzs_helper.rb
module OploverzsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sames_helper.rb
module SamesHelper
end

app/helpers/tonans_helper.rb
module TonansHelper
end

app/views/oploverzs/_form.html.erb
<%= form_for(oploverz) do |f| %>
  <% if oploverz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(oploverz.errors.count, "error") %> prohibited this oploverz from being saved:</h2>

      <ul>
      <% oploverz.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :sinops %>
    <%= f.text_area :sinops %>
  </div>

  <div class="field">
    <%= f.label :small %>
    <%= f.text_area :small %>
  </div>

  <div class="field">
    <%= f.label :medium %>
    <%= f.text_area :medium %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/oploverzs/_search.html.erb
<form class="form-inline">
  <div class="input-group">
    <%= form_tag oploverzs_path, :method => :get do %>
    <%= text_field_tag :q, "", class: "form-control", size: "90" , placeholder: "Search" %>
      <div class="input-group-btn">
          <%= button_tag "", :name => nil, class: "btn btn-primary glyphicon glyphicon-search", type: "submit" %>
      </div>
      <% end %>
    </div>
</form>
<br>

app/views/oploverzs/edit.html.erb
<h1>Editing Oploverz</h1>

<%= render 'form', oploverz: @oploverz %>

<%= link_to 'Show', @oploverz %> |
<%= link_to 'Back', oploverzs_path %>

app/views/oploverzs/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h1>Oploverz</h1>
    <!-- <%= render 'search' %> -->
  <div class="row">
    <div class="col-md-9">
      <table class="table table-hover table-condensed">
        <thead>
          <tr>
            <th>Preview</th>
            <th>Title</th>
            <th>Sinopsis</th>
          </tr>
        </thead>

        <tbody>
          <% @oploverzs.each do |oploverz| %>
            <tr>
              <td>
                <% if oploverz.oimages.empty? %>
                <%= image_tag "http://gsbikerstienen.be/data/uploads/images/leden/no_image.png", class: "thumbnail" %>
                <% else %>
                  <%= image_tag oploverz.oimages.first.url, class: "img-thumbnail", size: "300x300" %>
                  <% end %>
              </td>
              <td>
              <%= link_to oploverz.title, oploverz %> <br>
              <%= time_ago_in_words(oploverz.created_at) %> ago
              </td>
              <td><%= truncate(oploverz.sinops, length: 100) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= will_paginate @oploverzs, renderer: BootstrapPagination::Rails %>
      <br>
       <!-- link_to 'New Oploverz', new_oploverz_path -->
    </div>

    <div class="col-md-3">
      <div class="facebook">
        <iframe src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2Faragoto.net%2F&tabs&width=340&height=70&small_header=true&adapt_container_width=true&hide_cover=true&show_facepile=false&appId=194209290600422" width="340" height="70" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe>
      </div>
      <br>
      <div class="twitter">
        <a href="https://twitter.com/animesatu" class="twitter-follow-button" data-show-count="false">Follow @animeloop_in</a><script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
      </div>
      <div class="chatango">
        <%= render 'chatango' %>
      </div>
    </div>
  </div>
</div>

app/views/oploverzs/new.html.erb
<h1>New Oploverz</h1>

<%= render 'form', oploverz: @oploverz %>

<%= link_to 'Back', oploverzs_path %>

app/views/oploverzs/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="header">
    <h3 class="text-center">
      <%= @oploverz.title %>
    </h3>
  </div>

<br>

<div class="row">
  <div class="col-sm-6 col-xs-6 col-md-offset-3">
  <div class="embed-responsive embed-responsive-4by3">
    <% @ostreams.each do |ostream| %>
      <%= videojs_rails sources: { mp4: ostream.link }, controls: true, width: "480x480", class: "embed-responsive-item" %>
      <% end %>
  </div>
  </div>
</div>

  <div class="row">
    <div class="col-sm-10 col-xs-2">
      <div class="panel panel-default">
        <div class="panel-heading">Basic Information</div>
        <div class="panel-body">
          <%= @oploverz.sinops %>
        </div>
      </div>

      <div class="panel panel-info">
        <div class="panel-heading">
        <h3 class="panel-title">Guide</h3>
      </div>
        <div class="panel-body">
          <br>
            <p>Link Download Sesuai Urutan dari Sumbernya. Terima Kasih Karena Sudah Mendownload Disini. Jangan Lupa di Share yah ^^</p>
            <br>
            <p>Elsfile | Google Drive | DataFile | ZippyShare | Mirror</p>
            <br>
        </div>
    </div>

    <div class="panel panel-success">
    <div class="panel-heading">
        <h3 class="panel-title">Small Size Link</h3>
    </div>
      <div class="panel-body">
        <%= auto_link(@oploverz.small, :html => { :target => '_blank' }) %>
      </div>
    </div>
    <br>

    <div class="panel panel-success">
      <div class="panel-heading">
        <h3 class="panel-title">Medium Size Link</h3>
      </div>
      <div class="panel-body">
        <%= auto_link(@oploverz.medium, :html => { :target => '_blank' }) %>
      </div>
    </div>
       <!-- link_to 'Edit', edit_oploverz_path(@oploverz) -->
    </div>
  </div>
  <%= render 'disqus' %>
</div>
<br>