config/routes.rb
Rails.application.routes.draw do
  resources :movieus, only: [:index, :show]
  resources :sames, only: [:index, :show]
  resources :tonans, only: [:index, :show]
  resources :melodies, only: [:index, :show]
  resources :awsubs, only: [:index, :show]
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'

  root 'pages#home'

  resources :oploverzs, only: [:index, :show]
  end

app/models/aimage.rb
class Aimage < ApplicationRecord
  validates :url, :awsub_id, uniqueness: true
  belongs_to :awsub
end

app/models/awsub.rb
class Awsub < ApplicationRecord

  extend FriendlyId

  friendly_id :title, use: [:slugged, :history, :finders]

  def should_generate_new_friendly_id?
    title_changed?
  end

  validates :title, :asmall, :amedium, uniqueness: true
  validates :title,  presence: true
  has_many :aimages, dependent: :destroy

  # searchable do
  #   text :title
  # end
end

app/models/limage.rb
class Limage < ApplicationRecord
  belongs_to :same
  validates :url, :same_id, uniqueness: true
end

app/models/melody.rb
class Melody < ApplicationRecord

  extend FriendlyId

  friendly_id :mtitle, use: [:slugged, :history, :finders]

  def should_generate_new_friendly_id?
    mtitle_changed?
  end


  validates :mtitle, uniqueness: true
  validates :mtitle, presence: true

  has_many :mimages, dependent: :destroy

  # searchable do
  #   text :mtitle
  # end
end

app/models/mimage.rb
class Mimage < ApplicationRecord
  validates :url, :melody_id, uniqueness: true
  
  belongs_to :melody

end

app/models/movieu.rb
class Movieu < ApplicationRecord

  extend FriendlyId

  friendly_id :title, use: [:slugged, :history, :finders]

  def should_generate_new_friendly_id?
    title_changed?
  end

  validates :title, uniqueness: true
  validates :title, presence: true
  has_many :vimages, dependent: :destroy
  
end

app/models/oimage.rb
class Oimage < ApplicationRecord
  validates :url, :oploverz_id, uniqueness: true
  belongs_to :oploverz
end

app/models/oploverz.rb
class Oploverz < ApplicationRecord

  extend FriendlyId

  friendly_id :title, use: [:slugged, :history, :finders]

  def should_generate_new_friendly_id?
    title_changed?
  end

  validates :title, uniqueness: true
  validates :title, presence: true
  has_many :oimages, dependent: :destroy
  has_many :ostreams, dependent: :destroy

  # searchable do
  #   text :title
  # end
end

app/models/ostream.rb
class Ostream < ApplicationRecord
  belongs_to :oploverz

  validates :link, :oploverz_id, uniqueness: true
end

app/models/same.rb
class Same < ApplicationRecord

  extend FriendlyId

  friendly_id :title, use: [:slugged, :history, :finders]

  def should_generate_new_friendly_id?
    title_changed?
  end

  validates :title, uniqueness: true
  validates :title, presence: true
  has_many :limages, dependent: :destroy

  # searchable do
  #   text :title
  # end
end

app/models/timage.rb
class Timage < ApplicationRecord
  validates :url, :tonan_id, uniqueness: true
  belongs_to :tonan
end

app/models/tonan.rb
class Tonan < ApplicationRecord

  extend FriendlyId

  friendly_id :title, use: [:slugged, :history, :finders]

  def should_generate_new_friendly_id?
    title_changed?
  end

  validates :title, :small, uniqueness: true
  validates :title, presence: true
  has_many :timages, dependent: :destroy

  # searchable do
  #   text :title
  # end
end

app/models/vimage.rb
class Vimage < ApplicationRecord
  belongs_to :movieu
  validates :url, :movieu_id, uniqueness: true
  validates :url, presence: true
end

app/controllers/aw_searcher.rb
# class AwSearcher
#   attr_reader :params, :awsubs
#   def call params
#     @params = params
#     @awsubs = simple_search
#     self
#   end
#
#   def simple_search
#     Awsub.search do
#     fulltext params[:q]
#     paginate(:page => params[:page], :per_page => 7)
#     end.results
#   end
#
# end

app/controllers/op_searcher.rb
# class OpSearcher
#   attr_reader :params, :oploverzs
#   def call params
#     @params = params
#     @oploverzs = simple_search
#     self
#   end
#
#   def simple_search
#     Oploverz.search do
#       fulltext params[:q]
#       paginate(:page => params[:page], :per_page => 7)
#   end.results
# end
#
# end

app/helpers/awsubs_helper.rb
module AwsubsHelper
end

app/helpers/movieus_helper.rb
module MovieusHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sames_helper.rb
module SamesHelper
end

app/helpers/tonans_helper.rb
module TonansHelper
end

app/views/layouts/_footer.html.erb
<div class="footer-bottom">

	<div class="container">

		<div class="row">

			<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">

				<div class="copyright">

					© 2017 MyAnime All rights reserved

				</div>

			</div>

			<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">

				<div class="design">

					 <strong> Created by </strong> : <a><%= link_to "Stealer One", 'http://twitter.com/' %></a>

				</div>

			</div>

		</div>

	</div>
</div>

app/views/layouts/_header.html.erb
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Anime", root_path, class: "navbar-brand" %>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Oploverz", oploverzs_path %></li>
          <li><%= link_to "Samehadaku", sames_path %></li>
          <li><%= link_to "Melodysubs", melodies_path %></li>
          <li><%= link_to "Tonansubs", tonans_path %></li>
          <li><%= link_to "Awsubs", awsubs_path %></li>
          <li><%= link_to "Streaming", movieus_path %></li>
        </ul>
      </div>
    </div>
  </nav>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> Download Anime terbaru, action, comedy, harem, ecchi | oploverz, awsubs, samehadaku, tonansubs, melodysubs</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon.png' %>
  </head>

  <body>

    <%= render 'layouts/header' %>
        <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
  <h1>This is About Page</h1>

  find me now :D
</div>

app/views/pages/contact.html.erb
<div class="container">
  <h1>This is Contact Us Page</h1>
  <p>
    -No Data Yet-
  </p>
</div>

app/views/pages/home.html.erb
<div class="container text-center">
  <div class="row">
    <div class="col-sm-12 col-xs-12">
      <h3>Welcome to MyAnime site!</h3>
      <p><em>Silahkan pilih fansub yang kamu suka</em></p>
      <p>Update Setiap Waktu!</p>
      <br>
    </div>
  </div>
 <div class="row">
   <div class="col-sm-12 col-xs-12">
     <p><strong>AnimeSatu</strong></p><br>
     <%= link_to "#", target: :_blank do %>
      <%= image_tag "https://2.bp.blogspot.com/-tpWGSJFOJuw/WPR-lHwC_II/AAAAAAAAAUo/Tz5nsIGyAdMDkMFEz1BMf7gcq6wyj1uTgCLcB/s1600/Symbol_dragon.png", size: "100x100", class: "img-circle" %>
     <% end %>
   </div>
 </div>
 <br>
  <div class="row">
   <div class="col-sm-4 col-xs-4">
     <p><strong>Oploverz</strong></p><br>
     <%= link_to oploverzs_path, target: :_blank do %>
      <%= image_tag "https://2.bp.blogspot.com/-zr3W7ZmD9EQ/WPR-l1PnTpI/AAAAAAAAAU4/3LUYpOjE1Nc1iS9m-xJbhvB1Y8EMKiDvgCLcB/s1600/Symbol_fox.png", size: "100x100", class: "img-circle" %>
     <% end %>
   </div>
   <div class="col-sm-4 col-xs-4">
     <p><strong>STREAMING ONLY</strong></p><br>
     <%= link_to movieus_path, target: :_blank do %>
      <%= image_tag "https://3.bp.blogspot.com/-nFSgexclt-8/WPR-lbt8MDI/AAAAAAAAAUw/ko3aU0tFsqoVoBZrdr6jrHQbblMYYUGQwCLcB/s1600/Symbol_boar.png", size: "100x100", class: "img-circle" %>
     <% end %>
   </div>
   <div class="col-sm-4 col-xs-4">
     <p><strong>Melodysubs</strong></p><br>
     <%= link_to melodies_path, target: :_blank do %>
      <%= image_tag "https://4.bp.blogspot.com/-VhKJJbRU2ww/WPR-ltJaBlI/AAAAAAAAAU0/N6X3zBTuH3k0HfjFo6TwgM-0J65zLbUegCLcB/s1600/Symbol_goat.png", size: "100x100", class: "img-circle" %>
     <% end %>
   </div>
 </div>
 <br>
 <br>
 <br>
 <div class="row">
   <div class="col-sm-4 col-xs-4">
     <p><strong>Tonansubs</strong></p><br>
     <%= link_to tonans_path, target: :_blank do %>
      <%= image_tag "https://4.bp.blogspot.com/-wNxCZpV7aXw/WPR-mHXOC5I/AAAAAAAAAU8/-Z6-QTaaokc7C8iLA4GA845J6tKgNGrawCLcB/s1600/Symbol_of_Lion.png", size: "100x100", class: "img-circle" %>
     <% end %>
   </div>
   <div class="col-sm-4 col-xs-4">
     <p><strong>Samehadaku</strong></p><br>
     <%= link_to sames_path, target: :_blank do %>
      <%= image_tag "https://4.bp.blogspot.com/-l_QcigcvIAo/WPR-ma3J7nI/AAAAAAAAAVA/n9h9frE02aIaJ4fNPr-DyrFUungemBAZQCLcB/s1600/Symbol_serpent.png", size: "100x100", class: "img-circle" %>
     <% end %>
   </div>
   <div class="col-sm-4 col-xs-4">
     <p><strong>Awsubs</strong></p><br>
     <%= link_to awsubs_path, target: :_blank do %>
      <%= image_tag "https://1.bp.blogspot.com/--d4K_Uj2ze0/WPR-m9CrXEI/AAAAAAAAAVE/VFRRvC_8DPQQDTwul7okor2-ldiCfXymQCLcB/s1600/tumblr_inline_nh4nxivcUh1t7pj9e.png", size: "100x100", class: "img-circle" %>
     <% end %>
   </div>
 </div>

 <!-- Batas Container -->
</div>